# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/k8s/fastapi-k8s.yaml
  - infra/k8s/fastapi-monitor.yaml

images:
  - name: pigashit/audiophile-backend 
    newName: pigashit/audiophile-backend
    newTag: "2a0ba729317ea22bde4f072625eb0485a09becc0"
