# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/k8s/fastapi-k8s.yaml

images:
  - name: pigashit/audiophile-backend 
    newName: pigashit/audiophile-backend
    newTag: "e2827e4cbd5e85b596fb748fd62fd77f982b9db4"
