# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infra/k8s/fastapi-k8s.yaml

images:
  - name: pigashit/audiophile-backend 
    newName: pigashit/audiophile-backend
    newTag: "04b1cdb41823b3e74019be62a97a75dbe5706a5c"
