apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: monitoring 
  labels:
    release: prometheus-stack 
    app: fastapi
spec:
  
  namespaceSelector:
    matchNames:
      - default
  
  selector:
    matchLabels:
      app: fastapi

  endpoints:
  - port: http-web   
    path: /metrics   
    interval: 15s    
